#ifndef _POWER_CONFIG_H__
#define _POWER_CONFIG_H__

#include "app_config.h"

#define CORE_HIGH_MODE				0
#define CORE_USB_CRYSTA_FREE_MODE	1
#define CORE_ONLY_APLL_MODE			2
#define CORE_USER_MODE				3
#define CORE_SPDIF_OUT_MODE			4

#define SYS_CORE_SET_MODE			CORE_USER_MODE
#define SYS_CRYSTAL_FREQ			24*1000*1000

#if (SYS_CORE_SET_MODE == CORE_USER_MODE)
    #define SYS_CORE_DPLL_FREQ			288*1000
    #define SYS_CORE_APLL_FREQ			240*1000
    #define SYS_CORE_CLK_SELECT			PLL_CLK_MODE
    #define SYS_UART_CLK_SELECT			PLL_CLK_MODE
    #define SYS_USB_CLK_SELECT			PLL_CLK_MODE
    #define SYS_FLASH_CLK_SELECT		FSHC_PLL_CLK_MODE
    #define SYS_FLASH_FREQ_SELECT		96000000
    #define SYS_AUDIO_CLK_SELECT		PLL_CLK_MODE
#endif

#endif
